//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDTO
    {
        public CustomerDTO()
        {
            this.CustomerAddresses = new List<CustomerAddressDTO>();
            this.InStores = new List<InStoreDTO>();
            this.PurchaseOps = new List<PurchaseOpDTO>();
            this.SaleOrdres = new List<SaleOrderDTO>();
        }
    
        public string ID { get; set; }
        public string SimpleID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Zip { get; set; }
        public string CstType { get; set; }

        public virtual IList<CustomerAddressDTO> CustomerAddresses { get; set; }
        public virtual IList<InStoreDTO> InStores { get; set; }
        public virtual IList<PurchaseOpDTO> PurchaseOps { get; set; }
        public virtual IList<SaleOrderDTO> SaleOrdres { get; set; }
    }
}
