//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDTO
    {
        public EmployeeDTO()
        {
            this.SaleOrderDetail = new HashSet<SaleOrderDetailDTO>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string IDCard { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Race { get; set; }
        public string BloodType { get; set; }
        public string Degree { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Status { get; set; }
        public System.DateTime EmployeDate { get; set; }
        public System.DateTime DismissDate { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string DeptId { get; set; }
    
        public virtual DepartmentDTO Department { get; set; }
        public virtual ICollection<SaleOrderDetailDTO> SaleOrderDetail { get; set; }
    }
}
