//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStoreDTO
    {
        public InStoreDTO()
        {
            this.InStoreDetail = new HashSet<InStoreDetailDTO>();
        }
    
        public string ID { get; set; }
        public string Type { get; set; }
        public decimal Qty { get; set; }
        public decimal RetQty { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime Date { get; set; }
        public string Opor { get; set; }
        public string CustomerId { get; set; }
        public string ProductId { get; set; }
    
        public virtual CustomerDTO Customer { get; set; }
        public virtual ProductDTO Product { get; set; }
        public virtual ICollection<InStoreDetailDTO> InStoreDetail { get; set; }
    }
}
