//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionStockDTO
    {
        public PositionStockDTO()
        {
            this.SaleOutDetail = new HashSet<SaleOutDetailDTO>();
        }
    
        public string WarePositionId { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public decimal InQty { get; set; }
        public decimal OutQty { get; set; }
        public decimal StoQty { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual ProductDTO Product { get; set; }
        public virtual WarePositionDTO WarePosition { get; set; }
        public virtual ICollection<SaleOutDetailDTO> SaleOutDetail { get; set; }
    }
}
