//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using JXCProject.Infrastructure.CustomValidations;

    public partial class ProductDTO
    {
        public ProductDTO()
        {
            this.InStore = new HashSet<InStoreDTO>();
            this.PositionStock = new HashSet<PositionStockDTO>();
            this.PurchaseOpDetails = new HashSet<PurchaseOpDetailDTO>();
            this.SaleOrderDetail = new HashSet<SaleOrderDetailDTO>();
        }

        public string ID { get; set; }

        [Required(ErrorMessage = "必填")]
        public string Name { get; set; }

        [Required(ErrorMessage = "必填")]
        [StringLength(10,MinimumLength=1,ErrorMessage="不能超过10个字符")]
        public string SimpleName { get; set; }

        [Required(ErrorMessage = "必填")]
        public string Unit { get; set; }

        [Required(ErrorMessage = "必填")]
        public decimal TradePrice { get; set; }

        [Required(ErrorMessage = "必填")]
        public decimal RetailPrice { get; set; }

        [Required(ErrorMessage = "必填")]
        public string Specification { get; set; }

        public string Producer { get; set; }

        [Required(ErrorMessage = "必填")]
        public System.DateTime ProductDate { get; set; }

         [MustSelected(ErrorMessage = "必选")]
        public string ProductCategoryId { get; set; }

        public virtual ICollection<InStoreDTO> InStore { get; set; }
        public virtual ICollection<PositionStockDTO> PositionStock { get; set; }
        public virtual ProductCategoryDTO ProductCategory { get; set; }
        public virtual ICollection<PurchaseOpDetailDTO> PurchaseOpDetails { get; set; }
        public virtual ICollection<SaleOrderDetailDTO> SaleOrderDetail { get; set; }
    }
}
