//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryDTO
    {
        public ProductCategoryDTO()
        {
            this.Product = new HashSet<ProductDTO>();
        }
    
        public string ID { get; set; }
        public string ParentID { get; set; }
        public string CategoryName { get; set; }
        public string ParentName { get; set; }

        public virtual ICollection<ProductDTO> Product { get; set; }
    }
}
