//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOpDTO
    {
        public PurchaseOpDTO()
        {
            this.PurchaseOpDetails = new List<PurchaseOpDetailDTO>();
            this.Customer = new CustomerDTO();

        }
    
        public string ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Appor { get; set; }
        public System.DateTime AppDate { get; set; }
        public string Apror { get; set; }
        public Nullable<System.DateTime> AprDate { get; set; }
        public Nullable<System.DateTime> LateRecDate { get; set; }
        public string State { get; set; }
        public string Memo { get; set; }
        public string CustomerId { get; set; }

        public virtual List<PurchaseOpDetailDTO> PurchaseOpDetails { get; set; }
        public virtual CustomerDTO Customer { get; set; }
    }
}
