//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PurchaseOpDetailDTO
    {
        public PurchaseOpDetailDTO()
        {
            this.PurchaseOp = new PurchaseOpDTO();
            this.Product = new ProductDTO();
        }

        public string ID { get; set; }
        [Required(ErrorMessage="必填")]
        public decimal AppQty { get; set; }
        public decimal AprQty { get; set; }
        [Required(ErrorMessage = "必填")]
        public decimal StkPrice { get; set; }
        public Nullable<decimal> RecQty { get; set; }
        public string ProductId { get; set; }
        public string PurchaseOpId { get; set; }

        public virtual PurchaseOpDTO PurchaseOp { get; set; }
        public virtual ProductDTO Product { get; set; }
    }
}
