//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOutDTO
    {
        public SaleOutDTO()
        {
            this.SaleOutDetail = new HashSet<SaleOutDetailDTO>();
        }
    
        public string ID { get; set; }
        public string Type { get; set; }
        public decimal Qty { get; set; }
        public string FreightNo { get; set; }
        public string SendType { get; set; }
        public string Rceiver { get; set; }
        public string RevAddress { get; set; }
        public string RevZip { get; set; }
        public string RevPhone { get; set; }
        public string OutDate { get; set; }
        public string Opor { get; set; }
        public string ProductId { get; set; }
        public string SaleOrderId { get; set; }
    
        public virtual SaleOrderDetailDTO SaleOrderDetail { get; set; }
        public virtual ICollection<SaleOutDetailDTO> SaleOutDetail { get; set; }
    }
}
