//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOutDetailDTO
    {
        public string SaleOutId { get; set; }
        public string WarePositionId { get; set; }
        public string ProductId { get; set; }
        public decimal DetlQty { get; set; }
    
        public virtual PositionStockDTO PositionStock { get; set; }
        public virtual SaleOutDTO SaleOut { get; set; }
    }
}
