//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDTO
    {
        public SaleOrderDTO()
        {
            this.SaleOrderDetail = new HashSet<SaleOrderDetailDTO>();
        }
    
        public string ID { get; set; }
        public string SaleType { get; set; }
        public decimal SaleQty { get; set; }
        public decimal SaleAmount { get; set; }
        public System.DateTime SaleDate { get; set; }
        public decimal OutQty { get; set; }
        public string Opor { get; set; }
        public System.DateTime OpDate { get; set; }
        public string CustomerId { get; set; }
    
        public virtual CustomerDTO Customer { get; set; }
        public virtual ICollection<SaleOrderDetailDTO> SaleOrderDetail { get; set; }
    }
}
