//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetailDTO
    {
        public SaleOrderDetailDTO()
        {
            this.SaleOut = new HashSet<SaleOutDTO>();
        }
    
        public string ProductId { get; set; }
        public string SaleOrderId { get; set; }
        public decimal StoPrice { get; set; }
        public decimal SalePrice { get; set; }
        public decimal Discount { get; set; }
        public decimal OutQty { get; set; }
        public string Opor { get; set; }
        public System.DateTime OpDate { get; set; }
        public System.Guid EmpId { get; set; }
    
        public virtual EmployeeDTO Employee { get; set; }
        public virtual ProductDTO Product { get; set; }
        public virtual SaleOrderDTO SaleOrder { get; set; }
        public virtual ICollection<SaleOutDTO> SaleOut { get; set; }
    }
}
