//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXCProject.Services.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseDTO
    {
        public WareHouseDTO()
        {
            this.WarePosition = new HashSet<WarePositionDTO>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Linkman { get; set; }
        public string Opor { get; set; }
        public System.DateTime OperDate { get; set; }
    
        public virtual ICollection<WarePositionDTO> WarePosition { get; set; }
    }
}
