//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFHelloWorldClient.Hello {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hello.IHelloKetty")]
    public interface IHelloKetty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloKetty/Show", ReplyAction="http://tempuri.org/IHelloKetty/ShowResponse")]
        string Show();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloKettyChannel : WCFHelloWorldClient.Hello.IHelloKetty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloKettyClient : System.ServiceModel.ClientBase<WCFHelloWorldClient.Hello.IHelloKetty>, WCFHelloWorldClient.Hello.IHelloKetty {
        
        public HelloKettyClient() {
        }
        
        public HelloKettyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloKettyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloKettyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloKettyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Show() {
            return base.Channel.Show();
        }
    }
}
